alias p='sudo pacman'

alias pS='sudo pacman -S'
alias pSs='sudo pacman -Ss'
alias pSyyu='sudo pacman -Syyu'
alias pSyu='sudo pacman -Syu'
alias pSu='sudo pacman -Su'
alias pSy='sudo pacman -Sy'
alias pR='sudo pacman -R'
alias pRs='sudo pacman -Rs'
alias pRsu='sudo pacman -Rsu'
alias pRsc='sudo pacman -Rsc'
alias pF='sudo pacman -F'
alias pFy='sudo pacman -Fy'
alias pFyy='sudo pacman -Fyy'
alias pQ='sudo pacman -Q'
alias pU='sudo pacman -U'

