alias pm='sudo pacman'

alias ps='sudo pacman -S'
alias pss='sudo pacman -Ss'
alias pr='sudo pacman -R'
alias prs='sudo pacman -Rs'
alias prsu='sudo pacman -Rsu'
alias prsc='sudo pacman -Rsc'
alias pf='sudo pacman -F'
alias pq='sudo pacman -Q'

alias syyu='sudo pacman -Syyu'
alias syu='sudo pacman -Syu'
alias su='sudo pacman -Su'
alias sy='sudo pacman -Sy'
alias fy='sudo pacman -Fy'
alias fyy='sudo pacman -Fyy'
